ejemplo7/proyectouno/administrativo/urls.py
from django.urls import path
# se importa las vistas de la aplicación
from administrativo import views

urlpatterns = [
    path('', views.index, name='index'),
    path('detalle/matricula/<int:id>', views.detalle_matricula,
         name='detalle_matricula'),
    path('crear/nueva/matricula', views.crear_matricula,
         name='crear_matricula'),
    path('editar/matricula/<int:id>', views.editar_matricula,
         name='editar_matricula'),
    path('detalle/estudiante/<int:id>', views.detalle_estudiante,
         name='detalle_estudiante'),
    path('ver/modulos/', views.ver_modulos, name='ver_modulos'),
    path('crear/nuevo/modulo', views.crear_modulo,
         name='crear_modulo'),
    path('ver/estudiantes/', views.ver_estudiantes, name='ver_estudiantes'),
path('crear/nuevo/estudiante', views.crear_estudiante,
         name='crear_estudiante'),


]

ejemplo7/proyectouno/proyectouno/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('administrativo.urls')),
]

ejemplo7/proyectouno/administrativo/models.py
from django.db import models

# Create your models here.

class Estudiante(models.Model):
    opciones_tipo_estudiante = (
        ('becado', 'Estudiante Becado'),
        ('no-becado', 'Estudiante No Becado'),
        )

    nombre = models.CharField("Nombre de estudiante", max_length=30)
    apellido = models.CharField(max_length=30)
    cedula = models.CharField(max_length=30, unique=True)
    edad = models.IntegerField("edad de estudiante") # Verbose field names
    tipo_estudiante = models.CharField(max_length=30, \
            choices=opciones_tipo_estudiante)
    modulos = models.ManyToManyField('Modulo', through='Matricula')


    def __str__(self):
        return "%s - %s - %s - edad: %d - tipo: %s" % (self.nombre,
                self.apellido,
                self.cedula,
                self.edad,
                self.tipo_estudiante)

    def obtener_matriculas(self):
        return self.lasmatriculas.all()

    def obtener_valor_matriculas(self):
        valor_matriculas = 0
        for m in self.lasmatriculas.all():
            valor_matriculas += m.costo
        return valor_matriculas
        

class Modulo(models.Model):
    """
    """
    opciones_modulo = (
        ('1', 'Primero'),
        ('2', 'Segundo'),
        ('3', 'Tercero'),
        ('4', 'Cuarto'),
        ('5', 'Quinto'),
        ('6', 'Sexto'),
        )

    nombre = models.CharField(max_length=30, \
            choices=opciones_modulo)
    estudiantes = models.ManyToManyField(Estudiante, through='Matricula')

    def __str__(self):
        return "Módulo: %s" % (self.nombre)

    def obtener_valor_matriculas(self):
        valor_matriculas = 0
        for e in self.estudiantes.all():
            for m in e.obtener_matriculas():
                valor_matriculas += m.costo
        return valor_matriculas

class Matricula(models.Model):
    """
    """
    estudiante = models.ForeignKey(Estudiante, related_name='lasmatriculas',
            on_delete=models.CASCADE)
    modulo = models.ForeignKey(Modulo, related_name='lasmatriculas',
            on_delete=models.CASCADE)
    comentario = models.CharField(max_length=200)

    costo = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return "Matricula: Estudiante(%s) - Modulo(%s)" % \
                (self.estudiante, self.modulo.nombre)

ejemplo7/proyectouno/administrativo/forms.py
from django.forms import ModelForm
from django import forms

from administrativo.models import Matricula, Modulo, Estudiante


class MatriculaForm(ModelForm):

    def __init__(self, *args, **kwargs):
        super(MatriculaForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs.update({'class': 'form-control'})

    class Meta:
        model = Matricula
        fields = ['estudiante', 'modulo', 'comentario', 'costo']
        widgets = {
            'comentario': forms.Textarea(attrs={'class': 'form-control', 'rows': 2}),
        }


class MatriculaEditForm(ModelForm):

    def __init__(self, *args, **kwargs):
        super(MatriculaEditForm, self).__init__(*args, **kwargs)
        self.initial['estudiante'] = self.instance.estudiante
        self.fields["estudiante"].widget = forms.widgets.HiddenInput()
        self.initial['modulo'] = self.instance.modulo
        self.fields["modulo"].widget = forms.widgets.HiddenInput()
        for field in self.fields:
            self.fields[field].widget.attrs.update({'class': 'form-control'})

    class Meta:
        model = Matricula
        fields = ['estudiante', 'modulo', 'comentario', 'costo']
        widgets = {
            'comentario': forms.Textarea(attrs={
                'rows': 4,
                'cols': 40,
                'placeholder': 'Escribe aquí tu comentario...',
                'class': 'form-control'
            }), }


class ModuloForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super(ModuloForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs.update({'class': 'form-control'})

    class Meta:
        model = Modulo
        fields = ['nombre']


class EstudianteForm(ModelForm):

    def __init__(self, *args, **kwargs):
        super(EstudianteForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs.update({'class': 'form-control'})

    class Meta:
        model = Estudiante
        fields = ['nombre', 'nombre', 'apellido', 'cedula', 'edad', 'tipo_estudiante']

ejemplo7/proyectouno/administrativo/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.template import RequestContext
from django.shortcuts import render

# importar las clases de models.py
from administrativo.models import *
from administrativo.forms import *



# vista que permita presesentar las matriculas
def index(request):
    """
    """
    matriculas = Matricula.objects.all()

    titulo = "Listado de matriculas"
    informacion_template = {'matriculas': matriculas,
    'numero_matriculas': len(matriculas), 'mititulo': titulo}
    return render(request, 'index.html', informacion_template)


def detalle_matricula(request, id):
    """

    """

    matricula = Matricula.objects.get(pk=id)
    informacion_template = {'matricula': matricula}
    return render(request, 'detalle_matricula.html', informacion_template)


def crear_matricula(request):
    """
    """
    if request.method=='POST':
        formulario = MatriculaForm(request.POST)
        print(formulario.errors)
        if formulario.is_valid():
            formulario.save() # se guarda en la base de datos
            return redirect(index)
    else:
        formulario = MatriculaForm()
    diccionario = {'formulario': formulario}

    return render(request, 'crear_matricula.html', diccionario)

def editar_matricula(request, id):
    """
    """
    matricula = Matricula.objects.get(pk=id)
    print("----------matricula")
    print(matricula)
    print("----------matricula")
    if request.method=='POST':
        formulario = MatriculaEditForm(request.POST, instance=matricula)
        print(formulario.errors)
        if formulario.is_valid():
            formulario.save()
            return redirect(index)
    else:
        formulario = MatriculaEditForm(instance=matricula)
    diccionario = {'formulario': formulario}

    return render(request, 'editar_matricula.html', diccionario)

def detalle_estudiante(request, id):
    """

    """

    estudiante = Estudiante.objects.get(pk=id)
    informacion_template = {'e': estudiante}
    return render(request, 'detalle_estudiante.html', informacion_template)

# ver los módulos
#    nombre del módulp
#    valor de todas las matriculas del módulo

def ver_modulos(request):
    """
    """
    modulos = Modulo.objects.all()

    titulo = "Listado de módulos"
    informacion_template = {'modulos': modulos,
    'numero_modulos': len(modulos), 'mititulo': titulo}
    return render(request, 'ver_modulos.html', informacion_template)

# ver los estudiantes >> de los estudiantes debo visualizar:
#    nombre 
#    apellido
#    cedula
#    edad
#    tipo_estudiante 
#    costo de matriculas

def ver_estudiantes(request):
    """
    """
    estudiantes = Estudiante.objects.all()

    titulo = "Listado de Estudiantes"
    informacion_template = {'estudiantes': estudiantes,
    'numero_estudiantes': len(estudiantes), 'mititulo': titulo}
    return render(request, 'ver_estudiantes.html', informacion_template)

# crear módulos
def crear_modulo(request):
    """
    """
    if request.method=='POST':
        formulario = ModuloForm(request.POST)
        print(formulario.errors)
        if formulario.is_valid():
            formulario.save() # se guarda en la base de datos
            return redirect(index)
    else:
        formulario = ModuloForm()
    diccionario = {'formulario': formulario}

    return render(request, 'crear_modulo.html', diccionario)

# crear estudiantes
def crear_estudiante(request):
    """
    """
    if request.method=='POST':
        formulario = EstudianteForm(request.POST)
        print(formulario.errors)
        if formulario.is_valid():
            formulario.save() # se guarda en la base de datos
            return redirect(index)
    else:
        formulario = EstudianteForm()
    diccionario = {'formulario': formulario}

    return render(request, 'crear_estudiante.html', diccionario)

ejemplo7/proyectouno/administrativo/templates/crear_estudiante.html
{% extends "master.html" %}

{% block title %}
    Crear Estudiante
{% endblock %}

{% block content %}

    <div class="col-lg-4 col-md-6 col-12 mt-4">
        <a class="btn custom-btn custom-border-btn" href="{% url 'index' %}">Inicio</a>
    </div>

    <h2 class="mt-4">Crear Estudiante</h2>

        <form action="" method="post" class="custom-form contact-form" role="form">
            {% csrf_token %}
            {{ formulario.as_p }}
            <div class="col-lg-4 col-md-6 col-12">
                <button type="submit" class="form-control">Crear</button>
            </div>
        </form>
    </br>

{% endblock %}

ejemplo7/proyectouno/administrativo/templates/crear_matricula.html
{% extends "master.html" %}

{% block title %}
    Crear Matrícula
{% endblock %}

{% block content %}

    <div class="col-lg-4 col-md-6 col-12 mt-4">
        <a class="btn custom-btn custom-border-btn" href="{% url 'index' %}">Inicio</a>
    </div>

    <h2>Crear Matricula</h2>

    <form action="" method="post" class="custom-form">
        {% csrf_token %}
        {{ formulario.as_p }}
        <div class="col-lg-4 col-md-6 col-12">
            <button type="submit" class="form-control">Crear</button>
        </div>
    </form>
    </br>



{% endblock %}

ejemplo7/proyectouno/administrativo/templates/crear_modulo.html
{% extends "master.html" %}

{% block title %}
    Crear Módulo
{% endblock %}

{% block content %}

    <div class="col-lg-4 col-md-6 col-12 mt-4">
        <a class="btn custom-btn custom-border-btn" href="{% url 'index' %}">Inicio</a>
    </div>

    <h2>Crear Modulo</h2>

    <form action="" method="post" class="custom-form contact-form" role="form">
        {% csrf_token %}
        {{ formulario.as_p }}
        <div class="col-lg-4 col-md-6 col-12">
            <button type="submit" class="form-control">Crear</button>
        </div>
    </form>
    </br>

{% endblock %}

ejemplo7/proyectouno/administrativo/templates/detalle_estudiante.html
{% extends "master.html" %}

{% block title %}
    Detalle Estudiante
{% endblock %}

{% block content %}
    <h2>Detalle estudiante</h2>

    <h5 class="mt-4 mb-2">Nombre:</h5> <p>{{ e.nombre }}</p>
    </br>
    <h5 class="mt-4 mb-2">Apellido:</h5> <p>{{ e.apellido }}</p>
    </br>
    <h5 class="mt-4 mb-2">Edad:</h5> <p>{{ e.edad }}</p>
    </br>
    <h5 class="mt-4 mb-2">Cédula:</h5> <p>{{ e.cedula }}</p>
    </br>
    <hr>
    <table id="tabla_datos">
        <tr>
            <th><b>Módulo</b></th>
            <th><b>comentario</b></th>

        </tr>
        {% for m in e.obtener_matriculas %}
            <tr>
                <td>
                    {{ m.modulo.nombre }}
                </td>
                <td>
                    {{ m.comentario }}
                </td>

            </tr>
        {% endfor %}

    </table>

    </br>
    <div class="col-lg-4 col-md-6 col-12">
        <a class="btn custom-btn custom-border-btn ms-3" href="{% url 'index' %}">Inicio</a>
    </div>

    <script type="text/javascript">

        import $ from '../static/js/jquery.min';

        $(document).ready(function () {
            $('#tabla_datos').DataTable();
        });
    </script>
{% endblock %}

ejemplo7/proyectouno/administrativo/templates/detalle_matricula.html
{% extends "master.html" %}

{% block title %}
  Detalle Matrícula
{% endblock %}

{% block content %}

<h3>Detalle de Matricula</h3>

<h5 class="mt-4 mb-2">Nombre:</h5> <p>{{matricula.estudiante}}</p>
</br>
<h5 class="mt-4 mb-2">Módulo:</h5> <p>{{matricula.modulo}}</p>

</br>
<div class="col-lg-4 col-12">
  <a class="btn custom-btn custom-border-btn ms-3" href="{% url 'index' %}">Inicio</a>
</div>
{% endblock %}

ejemplo7/proyectouno/administrativo/templates/editar_matricula.html
{% extends "master.html" %}

{% block title %}
    Editar Matrícula
{% endblock %}

{% block content %}

    <div class="col-lg-4 col-md-6 col-12">
        <a class="btn custom-btn custom-border-btn" href="{% url 'index' %}">Inicio</a>
    </div>

    <h2>Editar Matricula</h2>

    <form action="" method="post" class="custom-form">
        {% csrf_token %}
        {{ formulario.as_p }}
        <div class="col-lg-4 col-md-6 col-12">
            <button type="submit" class="form-control">Actualizar</button>
        </div>
    </form>
    </br>
{% endblock %}

ejemplo7/proyectouno/administrativo/templates/index.html
{% extends "master.html" %}

{% block title %}
    Listado de Estudiantes
{% endblock %}

{% block content %}
    <h1>{{ mititulo }}</h1>
    <hr>
    <h3>Número de Matriculas {{ numero_matriculas }}</h3>
    <div class="col-lg-4 col-md-6 col-12 mb-3">
        <a class="btn custom-btn custom-border-btn" href="{% url 'crear_matricula' %}">Nueva Matrícula</a>
    </div>
    <hr>
    <table id="tabla_datos" class="cell-border">
        <thead>
        <tr>
            <th><b>Estudiante</b></th>
            <th><b>Módulo</b></th>
            <th><b>Comentario</b></th>
            <th><b>Opciones</b></th>
        </tr>
        </thead>
        {% for e in matriculas %}
            <tr>
                <td>
                    {{ e.estudiante.nombre }} <br>
                    {{ e.estudiante.get_tipo_estudiante_display }}
                    <a class="bi-person-fill" href="{% url 'detalle_estudiante' e.estudiante.id %}"></a>
                </td>
                <td>
                    {{ e.modulo.nombre }}
                </td>
                <td>
                    {{ e.comentario }}
                </td>
                <td>
      <span>
        <a class="bi-eye-fill" href="{% url 'detalle_matricula' e.id %}" title="ver"></a>
        <a class="bi-pencil-square" href="{% url 'editar_matricula' e.id %}" title="editar"></a>
      </span>
                </td>
            </tr>
        {% endfor %}

    </table>

    <script type="text/javascript">
        $(document).ready(function () {
            $('#tabla_datos').DataTable();
        });
    </script>
{% endblock %}

ejemplo7/proyectouno/administrativo/templates/master.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width"/>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600;700;800;900&display=swap"
          rel="stylesheet">
    {% load static %}

    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.25/css/jquery.dataTables.min.css">
    <script type="text/javascript" src="https://code.jquery.com/jquery-3.5.1.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/1.10.25/js/jquery.dataTables.min.js"></script>

    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/bootstrap-icons.css' %}" rel="stylesheet">
    <link href="{% static 'css/templatemo-topic-listing.css' %}" rel="stylesheet">

    <title>
        {% block title %}
        {% endblock %}
    </title>
</head>
<body>


<!-- ***** Header Area Start ***** -->
<header class="site-header d-flex flex-column justify-content-center align-items-center">
    <nav class="navbar navbar-expand-lg">
        <div class="container">
            <a class="navbar-brand" href="{% url 'index' %}">
                <i class="bi-back"></i>
                <span>MiApp</span>
            </a>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ms-lg-5 me-lg-auto">
                    <li class="nav-item">
                        <a class="nav-link click-scroll" href="{% url 'index' %}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link click-scroll {% if request.path == '/ver/modulos/' %} active {% endif %}" href="{% url 'ver_modulos' %}">Ver Módulos</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link click-scroll {% if request.path == '/ver/estudiantes/' %} active {% endif %}" href="{% url 'ver_estudiantes' %}">Ver Estudiantes</a>
                    </li>
                </ul>

                <div class="d-none d-lg-block">
                    <a href="#top" class="navbar-icon bi-person smoothscroll"></a>
                </div>
            </div>
        </div>
    </nav>


    <div class="container">
        <div class="row align-items-center">
            <div class="col-lg-5 col-12">
                <h6>Bienvenidos</h6>
                <h1 class="text-white">Aplicación Administivo Matrículas</h1>
            </div>
        </div>
    </div>
</header>
<!-- ***** Header Area End ***** -->

<section class="section-padding section-bg">
    <div class="container">
        <div class="row">
            {% block content %}
            {% endblock %}
        </div>
    </div>
</section>

<footer class="site-footer">
    <div class="container">
        <div class="row">
            <div class="col-lg-3 col-12 mb-4 pb-2">
                <p>Loja-Ecuador

                    <br>{% now "j F Y H:i" %}</p>
            </div>
        </div>
    </div>
</footer>
<!-- Scripts -->
<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'js/jquery.sticky.js' %}"></script>
<script src={% static  "js/click-scroll.js" %}></script>
<script src="{% static 'js/custom.js' %}"></script>


</body>
</html>

ejemplo7/proyectouno/administrativo/templates/ver_estudiantes.html
{% extends "master.html" %}

{% block title %}
    Ver Estudiantes
{% endblock %}

{% block content %}
    <h1>{{ mititulo }}</h1>
    <hr>
    <h3>Número de Estudiantes {{ numero_estudiantes }}</h3>
    <div class="col-lg-4 col-md-6 col-12 mb-3">
        <a class="btn custom-btn custom-border-btn" href="{% url 'crear_estudiante' %}">Nuevo estudiante</a>
    </div>
    <hr>

    <table id="tabla_datos" class="cell-border">
        <tr>
            <th><b>Nombre</b></th>
            <th><b>Apellido</b></th>
            <th><b>Cedula</b></th>
            <th><b>Edad</b></th>
            <th><b>Tipo</b></th>
            <th><b>Costo de Matriculas</b></th>
        </tr>
        {% for e in estudiantes %}
            <tr>
                <td>
                    {{ e.nombre }} <br>
                </td>
                <td>
                    {{ e.apellido }} <br>
                </td>
                <td>
                    {{ e.cedula }} <br>
                </td>
                <td>
                    {{ e.edad }} <br>
                </td>
                <td>
                    {{ e.get_tipo_estudiante_display }}
                </td>
                <td>
                    {{ e.obtener_valor_matriculas }}
                </td>
            </tr>
        {% endfor %}

    </table>
    <hr>



    <script type="text/javascript">

        $(document).ready(function () {
            $('#tabla_datos').DataTable();
        });

    </script>
{% endblock %}

ejemplo7/proyectouno/administrativo/templates/ver_modulos.html
{% extends "master.html" %}

{% block title %}
  Ver Módulos
{% endblock %}

{% block content %}
<h1>{{mititulo}}</h1>
<hr>
<h3>Número de Modulos {{ numero_modulos }}</h3>
<div class="col-lg-4 col-md-6 col-12 mb-3">
  <a class="btn custom-btn custom-border-btn" href="{% url 'crear_modulo' %}">Nuevo módulo</a>
</div>
<hr>
<table id="tabla_datos">
  <tr>
    <th><b>Módulo</b></th>
    <th><b>Valor en matrículas($)</b></th>
  </tr>
  {% for m in modulos %}
  <tr>
    <td>
      {{m.get_nombre_display}} <br>
    </td>
    <td>
      {{m.obtener_valor_matriculas}}
    </td>
  </tr>
  {% endfor %}

</table>
<hr>
<script type="text/javascript">
  $(document).ready( function () {
    $('#tabla_datos').DataTable();
  });
</script>
{% endblock %}